config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "refrigeration_time#index"
  get "/getOutTime",     to: "refrigeration_time#getOutTime",    as: :get_out_time
  post "/UpdateOutTime", to: "refrigeration_time#updateOutTime", as: :update_out_time
  post "/reset",         to: "refrigeration_time#reset",         as: :reset
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/refrigeration_time_controller.rb
class RefrigerationTimeController < ApplicationController
  def index
  end

  def updateOutTime
    updateParams = updateOutTimeParams
    item_id, location_id, timestamp = updateParams[:item_id], updateParams[:location_id], updateParams[:timestamp]

    sql = %{
      SELECT * 
      FROM cache_tables 
      WHERE item_id = #{item_id}
      LIMIT 1
    }

    # Queries
    cache_table_records = ActiveRecord::Base.connection.execute sql
    curr_location = Location.find(location_id)

    if cache_table_records.count == 0
      # If you don't have a cache_record => you are in a refrigerator
      new_time_outside = 0
      sql = %{
        INSERT INTO cache_tables (item_id, time_outside, prev_loc_is_freezer, last_time_stamp)
        VALUES (#{item_id}, #{new_time_outside}, #{curr_location[:is_freezer]}, #{timestamp})
      }
    else
      cache_table_record = cache_table_records.first
      new_time_outside = cache_table_record["time_outside"] 
      unless cache_table_record["prev_loc_is_freezer"]
        new_time_outside += (timestamp.to_i - cache_table_record["last_time_stamp"])
      end

      sql = %{
        UPDATE cache_tables
        SET time_outside        = #{new_time_outside},
            prev_loc_is_freezer = #{curr_location[:is_freezer]},
            last_time_stamp     = #{timestamp}
        WHERE item_id           = #{item_id}
      }
    end

    ActiveRecord::Base.connection.execute sql
    redirect_to get_out_time_path(item_id: item_id)
  end

  def getOutTime
    @item_id = getOutTimeParams[:item_id]

    sql = %{
      SELECT * 
      FROM cache_tables 
      WHERE item_id = #{@item_id}
      LIMIT 1
    }

    # Queries
    cache_table_record = ActiveRecord::Base.connection.execute sql
    @outTime = cache_table_record.count == 0 ? 0 : cache_table_record.first["time_outside"]
  end

  def reset
    sql = %{
      DELETE FROM cache_tables WHERE TRUE
    }
    ActiveRecord::Base.connection.execute sql
    
    redirect_to root_path
  end

  private
    def updateOutTimeParams
      params.permit(:item_id, :location_id, :timestamp)
    end
    
    def getOutTimeParams
      params.permit(:item_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/refrigeration_time_helper.rb
module RefrigerationTimeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Track Refrigeration Time App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/refrigeration_time/getOutTime.html.erb
<div>
    <h1>Item Id: <%= @item_id %> spent <%= @outTime %> seconds outside the refrigerator.</h1>
<div>

app/views/refrigeration_time/index.html.erb
<div class="container">
    <h1 class="display-3 my-2">Welcome to the Track Refrigeration Time App.</h1>

    <div>
      <ul>
        <li>Location Id [1, 6] inclusive are refrigerators.</li>
        <li>Location Id [7, 12] inclusive are not refrigerators.</li>
        <li>Reset will make total time spent outside a refrigerator equal to 0.</li>
        <li>Location Id's remain active even during the reset.</li>
      </ul>
    </div>

    <%= form_with url: update_out_time_path, class: "my-2", method: :post do |form| %>
        <%= form.label :item_id, "Item ID" %>
        <%= form.number_field :item_id %>
        <%= form.label :location_id, "Location ID" %>
        <%= form.number_field :location_id %>
        <%= form.label :timestamp, "Timestamp(in seconds)" %>
        <%= form.number_field :timestamp %>
        <%= form.submit "Update Out Time", class: "btn btn-primary" %>
    <% end %>

    <hr />
    <%= form_with url: get_out_time_path, class: "my-2", method: :get do |form| %>
        <%= form.label :item_id, "Item ID" %>
        <%= form.number_field :item_id %>
        <%= form.submit "Get Out Time", class: "btn btn-primary" %>
    <% end %>

    <hr />
    <%= form_with url: reset_path, class: "my-2", method: :post do |form| %>
        <%= form.submit "Reset", class: "btn btn-primary" %>
    <% end %>
</div>